import re
from datetime import date, datetime
from decimal import Decimal
from typing import Any
from uuid import UUID as PythonUUID

from pydantic import BaseModel, ConfigDict, computed_field, field_validator, model_validator

from Backend.api.leases.schemas import LeaseDocumentResponse
from Backend.api.accounting.payments.schemas import PaymentResponse
from Backend.api.accounting.invoices.schemas import InvoiceResponse
from Backend.api.maintenance.schemas import MaintenanceRequestResponse
from Backend.models.tenant import TenantStatus
from Backend.models.enums import TenantType


# === Emergency Contact Schemas ===
class EmergencyContactBase(BaseModel):
    """Base schema for emergency contact with validation."""
    name: str
    relationship: str
    phone: str
    email: str | None = None
    is_primary: bool = False
    notes: str | None = None

    @field_validator("name", "relationship")
    @classmethod
    def validate_required_fields(cls, v: str) -> str:
        """Validate that required fields are not empty."""
        if not v or not v.strip():
            raise ValueError("Field cannot be empty")
        return v.strip()

    @field_validator("phone")
    @classmethod
    def validate_phone_format(cls, v: str) -> str:
        """Validate phone number format."""
        if not v or not v.strip():
            raise ValueError("Phone number cannot be empty")
        # Must contain 10-15 digits
        digit_count = len(re.sub(r"[^0-9]", "", v))
        if not (10 <= digit_count <= 15):
            raise ValueError("Phone number must contain 10-15 digits")
        return v.strip()

    @field_validator("email")
    @classmethod
    def validate_email_format(cls, v: str | None) -> str | None:
        """Validate email format if provided."""
        if v is None or v == "":
            return None
        email = v.strip()
        if not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", email):
            raise ValueError("Invalid email format")
        return email


class EmergencyContactCreate(EmergencyContactBase):
    """Schema for creating a new emergency contact."""
    pass


class EmergencyContactUpdate(BaseModel):
    """Schema for updating an existing emergency contact (all fields optional)."""
    name: str | None = None
    relationship: str | None = None
    phone: str | None = None
    email: str | None = None
    is_primary: bool | None = None
    notes: str | None = None

    @field_validator("name", "relationship")
    @classmethod
    def validate_text_fields(cls, v: str | None) -> str | None:
        """Validate that text fields are not empty if provided."""
        if v is not None and (not v or not v.strip()):
            raise ValueError("Field cannot be empty if provided")
        return v.strip() if v else None

    @field_validator("phone")
    @classmethod
    def validate_phone_format(cls, v: str | None) -> str | None:
        """Validate phone number format if provided."""
        if v is None:
            return None
        if not v.strip():
            raise ValueError("Phone number cannot be empty if provided")
        digit_count = len(re.sub(r"[^0-9]", "", v))
        if not (10 <= digit_count <= 15):
            raise ValueError("Phone number must contain 10-15 digits")
        return v.strip()

    @field_validator("email")
    @classmethod
    def validate_email_format(cls, v: str | None) -> str | None:
        """Validate email format if provided."""
        if v is None or v == "":
            return None
        email = v.strip()
        if not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", email):
            raise ValueError("Invalid email format")
        return email


class EmergencyContactResponse(EmergencyContactBase):
    """Schema for emergency contact response with ID."""
    id: str  # UUID generated by frontend or backend

    model_config = ConfigDict(from_attributes=True)


# === Models ===
class PropertyResponseSimple(BaseModel):
    id: int
    name: str

    model_config = ConfigDict(from_attributes=True)


class UnitResponseSimple(BaseModel):
    id: int
    name: str  # Assuming unit has a 'name' or 'unit_number' field
    property: PropertyResponseSimple | None = None  # Nested property info

    model_config = ConfigDict(from_attributes=True)


class LeaseResponseSimple(BaseModel):
    id: int
    start_date: date
    end_date: date
    status: str
    monthly_rent: Decimal
    security_deposit: Decimal
    rent_due_day: int | None = None
    property_id: int
    unit_id: int | None = None
    property: PropertyResponseSimple | None = None
    unit: UnitResponseSimple | None = None
    documents: list[LeaseDocumentResponse] = []

    model_config = ConfigDict(from_attributes=True)


class TenantBase(BaseModel):
    tenant_type: TenantType = TenantType.INDIVIDUAL
    first_name: str | None = None
    last_name: str | None = None
    company_name: str | None = None
    contact_person: str | None = None
    phone: str | None = None  # Made optional per user feedback
    email: str
    status: TenantStatus = TenantStatus.ACTIVE
    user_id: PythonUUID | None = None
    current_property_id: int | None = None
    emergency_contacts: list[dict[str, Any]] = []

    @model_validator(mode="after")
    def validate_tenant_fields(self):
        """Validate required fields based on tenant type."""
        if self.tenant_type == TenantType.INDIVIDUAL:
            if not self.first_name or not self.first_name.strip():
                raise ValueError("First name is required for individual tenants")
            if not self.last_name or not self.last_name.strip():
                raise ValueError("Last name is required for individual tenants")
        elif self.tenant_type == TenantType.COMPANY:
            if not self.company_name or not self.company_name.strip():
                raise ValueError("Company name is required for company tenants")
        return self

    @field_validator("email")
    @classmethod
    def validate_email(cls, v: str) -> str:
        """
        Validates and normalizes an email address.
        
        Trims whitespace, converts the email to lowercase, and checks that it matches a standard email format. Raises a ValueError if the email is empty or invalid.
        """
        email = v.strip().lower()
        if not email:
            raise ValueError("Email cannot be empty")
        # Basic email validation
        if not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", email):
            raise ValueError("Invalid email format")
        return email

    @field_validator("first_name", "last_name", "company_name", "contact_person")
    @classmethod
    def validate_name_fields(cls, v: str | None) -> str | None:
        """
        Validates that name fields are not empty or only whitespace if provided.
        
        Returns the trimmed name if valid; raises ValueError if the input is empty or contains only whitespace.
        """
        if v is None:
            return v
        if v.strip() == "":
            raise ValueError("Name fields cannot be empty if provided")
        return v.strip()

    @field_validator("phone")
    @classmethod
    def validate_phone(cls, v: str | None) -> str | None:
        """
        Validates that a phone number contains 10 to 15 digits and only allowed formatting characters.
        
        The phone number may include digits, spaces, hyphens, parentheses, and a plus sign. Raises a ValueError if the digit count is outside the allowed range or if disallowed characters are present.
        """
        if v is None:
            return v
        # Single regex validation for both allowed characters and digit count
        # Pattern ensures 10-20 characters total with at least 10-15 digits
        if not re.fullmatch(r"^[\d\s\-\(\)\+]{10,20}$", v):
            raise ValueError("Phone number must be 10-20 characters long and contain only digits, spaces, hyphens, parentheses, and plus signs")
        
        # Verify digit count is within range
        digit_count = len(re.sub(r"[^0-9]", "", v))
        if not (10 <= digit_count <= 15):
            raise ValueError("Phone number must contain 10-15 digits")
        
        return v.strip()


class TenantCreate(TenantBase):
    # Allow receiving full_name from frontend for backward compatibility
    full_name: str | None = None
    # Make all fields required except these optional ones
    current_property_id: int | None = None
    user_id: PythonUUID | None = None

    @model_validator(mode="before")
    @classmethod
    def split_full_name(cls, data: dict) -> dict:
        """
        Extracts first and last names from a 'full_name' field in input data if separate fields are missing.
        
        If 'full_name' is present and both 'first_name' and 'last_name' are absent, splits 'full_name' into first and last names, assigns them to the corresponding fields, and removes 'full_name' from the data.
        """
        if isinstance(data, dict):
            full_name = data.get("full_name")
            first_name = data.get("first_name")
            last_name = data.get("last_name")
            tenant_type = data.get("tenant_type", "Individual")

            # Only split full_name if tenant is individual type and names are missing
            if (full_name and not first_name and not last_name and 
                (tenant_type == TenantType.INDIVIDUAL or tenant_type == TenantType.INDIVIDUAL.value)):
                names = full_name.split(" ", 1)
                data["first_name"] = names[0]
                if len(names) > 1:
                    data["last_name"] = names[1]
                else:
                    # Use the first name as last name if no space is found
                    # This prevents empty last_name validation errors
                    data["last_name"] = names[0]
        return data


class TenantBaseOptional(BaseModel):
    tenant_type: TenantType | None = None
    first_name: str | None = None
    last_name: str | None = None
    company_name: str | None = None
    contact_person: str | None = None
    phone: str | None = None
    email: str | None = None
    status: TenantStatus | None = None
    current_property_id: int | None = None
    emergency_contacts: list[dict[str, Any]] | None = None

    @field_validator("email")
    @classmethod
    def validate_email(cls, v: str | None) -> str | None:
        """
        Validates and normalizes an email address.
        
        Trims whitespace, converts to lowercase, and checks that the email is non-empty and matches a standard email pattern. Returns the normalized email or None if input is None.
        
        Raises:
            ValueError: If the email is empty or does not match the required format.
        """
        if v is None:
            return v
        if not v:
            raise ValueError("Email cannot be empty")
        email = v.strip().lower()
        if not re.match(r"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", email):
            raise ValueError("Invalid email format")
        return email

    @field_validator("first_name", "last_name", "company_name", "contact_person")
    @classmethod
    def validate_name_fields(cls, v: str | None) -> str | None:
        """
        Validates that name fields are not empty or whitespace if provided.
        
        Returns the trimmed name if valid, or None if the input is None. Raises a ValueError if the name is empty or contains only whitespace.
        """
        if v is None:
            return v
        if v.strip() == "":
            raise ValueError("Name fields cannot be empty if provided")
        return v.strip()

    @field_validator("phone")
    @classmethod
    def validate_phone(cls, v: str | None) -> str | None:
        """
        Validates that a phone number contains 10 to 15 digits and only allowed characters.
        
        Returns the trimmed phone number if valid, or None if input is None.
        
        Raises:
            ValueError: If the phone number does not contain 10-15 digits or contains invalid characters.
        """
        if v is None:
            return v
        # Single regex validation for both allowed characters and digit count
        # Pattern ensures 10-20 characters total with at least 10-15 digits
        if not re.fullmatch(r"^[\d\s\-\(\)\+]{10,20}$", v):
            raise ValueError("Phone number must be 10-20 characters long and contain only digits, spaces, hyphens, parentheses, and plus signs")
        
        # Verify digit count is within range
        digit_count = len(re.sub(r"[^0-9]", "", v))
        if not (10 <= digit_count <= 15):
            raise ValueError("Phone number must contain 10-15 digits")
        
        return v.strip()


class TenantUpdate(TenantBaseOptional):
    full_name: str | None = None

    @model_validator(mode="before")
    @classmethod
    def split_full_name_update(cls, data: dict) -> dict:
        """
        Splits a 'full_name' field into 'first_name' and 'last_name' if they are not already provided.
        
        If 'full_name' exists in the input dictionary and neither 'first_name' nor 'last_name' are present,
        the function splits 'full_name' at the first space and assigns the resulting parts to 'first_name'
        and 'last_name' respectively. The 'full_name' key is removed from the dictionary.
        """
        if (
            not isinstance(data, dict)
            or "full_name" not in data
            or not data["full_name"]
        ):
            return data

        full_name = data.pop("full_name")
        tenant_type = data.get("tenant_type", "Individual")

        # Only split for individual tenants
        if (data.get("first_name") is not None or data.get("last_name") is not None or
            (tenant_type != TenantType.INDIVIDUAL and tenant_type != TenantType.INDIVIDUAL.value)):
            return data

        names = full_name.split(" ", 1)
        data["first_name"] = names[0]
        data["last_name"] = names[1] if len(names) > 1 else data.get("last_name")

        return data


class PaymentPerformanceMetrics(BaseModel):
    """Payment performance metrics for tenant"""
    rate: int | None = None
    on_time_count: int = 0
    total_count: int = 0
    avg_days_early: int = 0
    status: str = 'no_data'  # 'excellent', 'good', 'needs_attention', 'no_data'


class OpenBalanceMetrics(BaseModel):
    """Open balance metrics for tenant"""
    total_balance: Decimal = Decimal('0')
    overdue_balance: Decimal = Decimal('0')
    rent_balance: Decimal = Decimal('0')
    invoice_balance: Decimal = Decimal('0')
    unpaid_invoice_count: int = 0
    is_overdue: bool = False
    next_due_amount: Decimal | None = None
    next_due_date: date | None = None


class TicketResolutionMetrics(BaseModel):
    """Ticket resolution metrics for tenant"""
    avg_days: float | None = None
    completed_count: int = 0
    total_count: int = 0
    pending_count: int = 0
    status: str = 'no_data'  # 'excellent', 'good', 'needs_improvement', 'no_data'


class UpcomingEventResponse(BaseModel):
    """Upcoming event for tenant"""
    id: str
    type: str  # 'rent', 'lease_expiry', 'invoice', 'insurance', 'maintenance'
    title: str
    subtitle: str
    date: date
    days_remaining: int
    amount: Decimal | None = None
    urgency: str  # 'critical', 'high', 'medium', 'low'
    icon: str  # 'money', 'document', 'alert', 'tool', 'shield'
    color: str
    bg_color: str


class TenantMetricsResponse(BaseModel):
    """Pre-calculated metrics for tenant to reduce client-side processing"""
    payment_performance: PaymentPerformanceMetrics
    open_balance: OpenBalanceMetrics
    ticket_resolution: TicketResolutionMetrics
    upcoming_events: list[UpcomingEventResponse] = []


class TenantResponse(BaseModel):
    id: int
    tenant_type: TenantType
    first_name: str | None = None
    last_name: str | None = None
    company_name: str | None = None
    contact_person: str | None = None
    phone: str | None = None
    email: str | None = None
    status: TenantStatus
    created_at: datetime
    updated_at: datetime
    current_property_id: int | None = None
    emergency_contacts: list[dict[str, Any]] = []
    # Add fields for unit and property
    unit: UnitResponseSimple | None = None
    property: PropertyResponseSimple | None = None
    # Add lease information
    leases: list[LeaseResponseSimple] = []
    # Add relationship data for metrics calculation
    payments: list[PaymentResponse] = []
    invoices: list[InvoiceResponse] = []
    maintenance_requests: list[MaintenanceRequestResponse] = []

    model_config = ConfigDict(from_attributes=True)

    def _get_individual_name(self) -> str:
        """
        Helper method to format individual tenant name.
        
        Returns the formatted name for individual tenants or a default fallback.
        """
        if self.first_name and self.last_name:
            return f"{self.first_name} {self.last_name}".strip()
        elif self.first_name:
            return self.first_name
        elif self.last_name:
            return self.last_name
        return "Individual Tenant"

    @computed_field
    def full_name(self) -> str:
        """
        Returns the tenant's full name or company name as appropriate.
        
        For individual tenants, concatenates first and last names.
        For company tenants, returns the company name or contact person info.
        """
        if self.tenant_type == TenantType.COMPANY:
            if self.company_name:
                if self.contact_person:
                    return f"{self.company_name} (Contact: {self.contact_person})"
                return self.company_name
            return self.contact_person or "Company Tenant"
        else:
            return self._get_individual_name()

    @computed_field  
    def display_name(self) -> str:
        """
        Returns the primary display name for the tenant.
        
        For company tenants, returns company name.
        For individual tenants, returns full name without contact info.
        """
        if self.tenant_type == TenantType.COMPANY:
            return self.company_name or "Company Tenant"
        else:
            return self._get_individual_name()


class TenantBulkDeleteRequest(BaseModel):
    tenant_ids: list[int]
