"""add_expense_tax_details_table_and_update_expenses

Revision ID: 0ae9ec6ef664
Revises: 4483ad5df02d
Create Date: 2025-06-04 03:07:32.555894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # Ensure sqlmodel is imported if its types are used indirectly


# revision identifiers, used by Alembic.
revision: str = '0ae9ec6ef664'
# Should be the last successfully applied migration
down_revision: Union[str, None] = '4483ad5df02d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create expense_tax_details table
    op.create_table('expense_tax_details',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('tax_name', sa.String(), nullable=False),
                    sa.Column('tax_rate', sa.Float(), nullable=False),
                    sa.Column('tax_amount', sa.Float(), nullable=False),
                    sa.Column('expense_id', sa.Integer(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['expense_id'], ['expenses.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    # Modify expenses table
    # Rename 'amount' to 'total_amount' first, as this might be needed for data migration
    op.alter_column('expenses', 'amount',
                    new_column_name='total_amount', existing_type=sa.Float())

    # Data migration: Populate NULL subtotal_amount from total_amount (the old 'amount')
    # This assumes that for old records, the 'amount' was effectively the subtotal if no detailed tax was specified.
    op.execute('UPDATE expenses SET subtotal_amount = total_amount WHERE subtotal_amount IS NULL AND total_amount IS NOT NULL')
    # Fallback for any remaining NULLs in subtotal_amount (e.g. if total_amount was also NULL, though less likely)
    op.execute(
        'UPDATE expenses SET subtotal_amount = 0.0 WHERE subtotal_amount IS NULL')

    # Now, make 'subtotal_amount' non-nullable
    op.alter_column('expenses', 'subtotal_amount',
                    existing_type=sa.Float(),
                    nullable=False)

    # Add 'total_tax_amount' column
    op.add_column('expenses', sa.Column('total_tax_amount',
                  sa.Float(), nullable=False, server_default=sa.text("'0.0'")))

    # Drop old single tax columns
    op.drop_column('expenses', 'tax_type')
    op.drop_column('expenses', 'tax_rate')
    # The old 'tax_amount' column (single tax)
    op.drop_column('expenses', 'tax_amount')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back old single tax columns to expenses table
    op.add_column('expenses', sa.Column(
        'tax_amount', sa.FLOAT(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column(
        'tax_rate', sa.FLOAT(), autoincrement=False, nullable=True))
    op.add_column('expenses', sa.Column(
        'tax_type', sa.VARCHAR(), autoincrement=False, nullable=True))

    # Drop 'total_tax_amount' column
    op.drop_column('expenses', 'total_tax_amount')

    # Rename 'total_amount' back to 'amount'
    op.alter_column('expenses', 'total_amount',
                    new_column_name='amount', existing_type=sa.Float())

    # Revert 'subtotal_amount' to nullable
    # This assumes it was nullable before this upgrade. If it was created non-nullable by an earlier unrecorded step, this might be an issue.
    # Given it was defined as nullable in the single-tax feature model, this should be correct.
    op.alter_column('expenses', 'subtotal_amount',
                    existing_type=sa.Float(),
                    nullable=True)

    # Drop expense_tax_details table
    op.drop_table('expense_tax_details')
    # ### end Alembic commands ###
