"""Beta Sync

Revision ID: 314d2daafae0
Revises: a5484c9a1708
Create Date: 2025-04-16 14:38:43.813878

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314d2daafae0'
down_revision: Union[str, None] = 'a5484c9a1708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('users', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('users', 'state')
    op.drop_column('users', 'zip_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'province')
    # ### end Alembic commands ###
