"""Added tenant name to Payment model

Revision ID: 3fcfe989bd1f
Revises: b1c050b82416
Create Date: 2025-04-15 23:40:45.256012

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fcfe989bd1f'
down_revision: Union[str, None] = 'b1c050b82416'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('tenant_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'tenant_name')
    # ### end Alembic commands ###
