"""Major reworks for Accounting

Revision ID: 498bda312b0f
Revises: e71957301ba0
Create Date: 2025-04-15 03:24:10.419700

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '498bda312b0f'
down_revision: Union[str, None] = 'e71957301ba0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_unit_link',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.Column('assigned_date', sa.DateTime(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['property_units.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'unit_id')
    )
    op.add_column('property_units', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('property_units', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('property_units', sa.Column('size', sa.Float(), nullable=True))
    op.add_column('property_units', sa.Column('monthly_rent', sa.Float(), nullable=True))
    op.add_column('property_units', sa.Column('is_rented', sa.Boolean(), nullable=False))
    op.alter_column('property_units', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_property_units_name'), 'property_units', ['name'], unique=False)
    op.drop_column('property_units', 'unit_number')
    op.drop_column('property_units', 'square_feet')
    op.drop_column('property_units', 'is_occupied')
    op.drop_column('property_units', 'rent_amount')
    
    # Add first_name and last_name as nullable first
    op.add_column('tenants', sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('tenants', sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    
    # Update existing records to split full_name into first_name and last_name
    op.execute("""
        UPDATE tenants 
        SET 
            first_name = SPLIT_PART(full_name, ' ', 1),
            last_name = SUBSTRING(full_name FROM POSITION(' ' IN full_name) + 1)
        WHERE full_name IS NOT NULL
    """)
    
    # Set default values for any NULL first_name or last_name
    op.execute("""
        UPDATE tenants 
        SET first_name = 'Unknown' 
        WHERE first_name IS NULL OR first_name = ''
    """)
    
    op.execute("""
        UPDATE tenants 
        SET last_name = 'Tenant' 
        WHERE last_name IS NULL OR last_name = ''
    """)
    
    # Create users for tenants that don't have a user_id
    op.execute("""
        WITH new_users AS (
            INSERT INTO users (
                email, 
                hashed_password, 
                first_name, 
                last_name, 
                user_type, 
                created_at, 
                updated_at
            )
            SELECT 
                -- Create a unique email based on tenant ID
                'tenant_' || t.id || '@example.com' as email,
                -- Default hashed password
                '$2b$12$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36WQoeG6Lruj3vjPGga31lW' as hashed_password,
                t.first_name,
                t.last_name,
                'TENANT' as user_type,
                NOW() as created_at,
                NOW() as updated_at
            FROM tenants t
            WHERE t.user_id IS NULL
            RETURNING id, email
        )
        UPDATE tenants t
        SET user_id = nu.id
        FROM new_users nu
        WHERE nu.email = 'tenant_' || t.id || '@example.com'
        AND t.user_id IS NULL
    """)
    
    # Now make the columns NOT NULL
    op.alter_column('tenants', 'first_name', nullable=False)
    op.alter_column('tenants', 'last_name', nullable=False)
    op.alter_column('tenants', 'user_id', existing_type=sa.INTEGER(), nullable=False)
    
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=True)
    op.drop_constraint('tenants_unit_id_fkey', 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'unit_id')
    op.drop_column('tenants', 'unit')
    op.drop_column('tenants', 'lease_start')
    op.drop_column('tenants', 'lease_end')
    op.drop_column('tenants', 'notes')
    op.drop_column('tenants', 'full_name')
    op.drop_column('tenants', 'monthly_rent')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('monthly_rent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('lease_end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('lease_start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('unit', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('unit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tenants_unit_id_fkey', 'tenants', 'property_units', ['unit_id'], ['id'])
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.alter_column('tenants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('tenants', 'last_name')
    op.drop_column('tenants', 'first_name')
    op.add_column('property_units', sa.Column('rent_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('property_units', sa.Column('is_occupied', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('property_units', sa.Column('square_feet', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('property_units', sa.Column('unit_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_property_units_name'), table_name='property_units')
    op.alter_column('property_units', 'property_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('property_units', 'is_rented')
    op.drop_column('property_units', 'monthly_rent')
    op.drop_column('property_units', 'size')
    op.drop_column('property_units', 'description')
    op.drop_column('property_units', 'name')
    op.drop_table('tenant_unit_link')
    # ### end Alembic commands ###
