"""Upgrade Property model for production (Multi-Landlord)

Revision ID: 4a41c64e899e
Revises: 1e9295f4131b
Create Date: 2025-05-04 12:25:42.855822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4a41c64e899e'
down_revision: Union[str, None] = '1e9295f4131b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('user_id', sa.Integer(), nullable=False))
    op.alter_column('properties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'province',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # First, create the enum type explicitly (in case Alembic doesn't try to)
    propertystatus = sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='propertystatus')
    propertystatus.create(op.get_bind(), checkfirst=True)

    # Now alter the column using explicit cast
    op.execute("ALTER TABLE properties ALTER COLUMN status TYPE propertystatus USING status::propertystatus"),
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('properties', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint('properties_owner_id_fkey', 'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'users', ['user_id'], ['id'])
    op.drop_column('properties', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key('properties_owner_id_fkey', 'properties', 'users', ['owner_id'], ['id'])
    op.alter_column('properties', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('properties', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('properties', 'status',
               existing_type=sa.Enum('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='propertystatus', create_constraint=True),
               type_=sa.VARCHAR(),
               nullable=True)
    op.alter_column('properties', 'property_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'postal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'province',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'city',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('properties', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('properties', 'user_id')
    # ### end Alembic commands ###
