"""Fix PropertyUnit.tenant <-> Tenant.assigned_units relationship

Revision ID: 5430370e8002
Revises: b4637ec85bb2
Create Date: 2025-04-20 06:28:16.370940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5430370e8002'
down_revision: Union[str, None] = 'b4637ec85bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_unit_link', sa.Column('start_date', sa.DateTime(), nullable=True))
    op.add_column('tenant_unit_link', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.drop_column('tenant_unit_link', 'is_primary')
    op.drop_column('tenant_unit_link', 'assigned_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenant_unit_link', sa.Column('assigned_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tenant_unit_link', sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('tenant_unit_link', 'end_date')
    op.drop_column('tenant_unit_link', 'start_date')
    # ### end Alembic commands ###
