"""Update tenant model: add phone, email, property_id

Revision ID: 6e85a0b7b420
Revises: 45c45f9f4604
Create Date: 2025-04-08 04:51:57.789335

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e85a0b7b420'
down_revision: Union[str, None] = '45c45f9f4604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('current_property_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'properties', ['current_property_id'], ['id'])
    op.drop_column('tenants', 'emergency_contact_phone')
    op.drop_column('tenants', 'emergency_contact_relationship')
    op.drop_column('tenants', 'emergency_contact_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('emergency_contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('emergency_contact_relationship', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('emergency_contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'current_property_id')
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'phone_number')
    # ### end Alembic commands ###
