"""sync_with_current_models

Revision ID: 6f886b1dbf6f
Revises: 4a41c64e899e
Create Date: 2025-05-12 22:04:58.446953

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f886b1dbf6f'
down_revision: Union[str, None] = '4a41c64e899e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create enum type if it doesn't exist
    vendorstatus = postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', 'INACTIVE', name='vendorstatus', create_type=False)
    vendorstatus.create(op.get_bind(), checkfirst=True)
    
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('business_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tax_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', vendorstatus, nullable=False),
    sa.Column('insurance_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insurance_policy_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('insurance_expiry_date', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('property_vendor_links',
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'vendor_id')
    )
    op.create_table('vendor_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('document_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'expenses', 'vendors', ['vendor_id'], ['id'])
    op.alter_column('lease_documents', 'lease_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('lease_documents_lease_id_fkey', 'lease_documents', type_='foreignkey')
    op.create_foreign_key(None, 'lease_documents', 'leases', ['lease_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_leases_property_id'), 'leases', ['property_id'], unique=False)
    op.create_index(op.f('ix_leases_status'), 'leases', ['status'], unique=False)
    op.create_index(op.f('ix_leases_tenant_id'), 'leases', ['tenant_id'], unique=False)
    op.drop_constraint('payments_tenant_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['tenant_id'], ['id'])
    op.alter_column('properties', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='propertystatus'),
               nullable=False)
    op.drop_constraint('property_units_property_id_fkey', 'property_units', type_='foreignkey')
    op.create_foreign_key(None, 'property_units', 'properties', ['property_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.drop_constraint('tenants_current_property_id_fkey', 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'properties', ['current_property_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'auth_provider_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_provider_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key('tenants_current_property_id_fkey', 'tenants', 'properties', ['current_property_id'], ['id'])
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_constraint(None, 'property_units', type_='foreignkey')
    op.create_foreign_key('property_units_property_id_fkey', 'property_units', 'properties', ['property_id'], ['id'])
    op.alter_column('properties', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='propertystatus'),
               nullable=True)
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_tenant_id_fkey', 'payments', 'tenants', ['tenant_id'], ['id'])
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_status'), table_name='leases')
    op.drop_index(op.f('ix_leases_property_id'), table_name='leases')
    op.drop_constraint(None, 'lease_documents', type_='foreignkey')
    op.create_foreign_key('lease_documents_lease_id_fkey', 'lease_documents', 'leases', ['lease_id'], ['id'])
    op.alter_column('lease_documents', 'lease_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_table('vendor_documents')
    op.drop_table('property_vendor_links')
    op.drop_table('vendors')
    # ### end Alembic commands ###
