"""sync with Supabase schema and auth

Revision ID: 77576eb47c7e
Revises: 4a41c64e899e
Create Date: 2025-05-13 00:15:03.300349

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77576eb47c7e'
down_revision: Union[str, None] = '4a41c64e899e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # --- 1. Drop FKs referencing users.id ---
    op.drop_constraint('invoices_tenant_id_fkey',
                       'invoices', type_='foreignkey')
    op.drop_constraint('payments_tenant_id_fkey',
                       'payments', type_='foreignkey')
    op.drop_constraint('properties_user_id_fkey',
                       'properties', type_='foreignkey')
    op.drop_constraint('tenants_user_id_fkey', 'tenants', type_='foreignkey')
    op.drop_constraint('lease_documents_uploaded_by_id_fkey',
                       'lease_documents', type_='foreignkey')
    # (add any other FKs referencing users.id as needed)

    # --- 2. Change users.id type first ---
    op.alter_column('users', 'id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=False,
                    existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))

    # --- 3. Change referencing columns ---
    op.alter_column('invoices', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    nullable=True)
    op.alter_column('payments', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    nullable=True)
    op.alter_column('properties', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=False)
    op.alter_column('tenants', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=True)
    op.alter_column('lease_documents', 'uploaded_by_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    nullable=True)

    # --- 4. Re-create FKs ---
    op.create_foreign_key('invoices_tenant_id_fkey', 'invoices', 'users', [
                          'tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('payments_tenant_id_fkey', 'payments', 'users', [
                          'tenant_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('properties_user_id_fkey', 'properties', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('tenants_user_id_fkey', 'tenants', 'users', [
                          'user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('lease_documents_uploaded_by_id_fkey', 'lease_documents', 'users', [
                          'uploaded_by_id'], ['id'], ondelete='SET NULL')
    # (add any other FKs referencing users.id as needed)

    op.drop_column('expenses', 'vendor_id')
    op.alter_column('invoices', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    nullable=True)
    op.drop_constraint('invoices_tenant_id_fkey',
                       'invoices', type_='foreignkey')
    op.create_foreign_key(None, 'invoices', 'users', [
                          'tenant_id'], ['id'], ondelete='SET NULL')
    op.alter_column('lease_documents', 'lease_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    op.alter_column('lease_documents', 'uploaded_by_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    nullable=True)
    op.drop_constraint('lease_documents_lease_id_fkey',
                       'lease_documents', type_='foreignkey')
    op.drop_constraint('lease_documents_uploaded_by_id_fkey',
                       'lease_documents', type_='foreignkey')
    op.create_foreign_key(None, 'lease_documents', 'leases', [
                          'lease_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'lease_documents', 'users', [
                          'uploaded_by_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_leases_property_id'),
                    'leases', ['property_id'], unique=False)
    op.create_index(op.f('ix_leases_status'),
                    'leases', ['status'], unique=False)
    op.create_index(op.f('ix_leases_tenant_id'),
                    'leases', ['tenant_id'], unique=False)
    op.add_column('payments', sa.Column(
        'description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('payments', 'payment_date',
                    existing_type=postgresql.TIMESTAMP(),
                    type_=sa.Date(),
                    existing_nullable=False)
    op.alter_column('payments', 'status',
                    existing_type=postgresql.ENUM(
                        'PENDING', 'PAID', 'LATE', 'PARTIAL', 'OVERDUE', 'REFUNDED', name='paymentstatus'),
                    nullable=True)
    op.alter_column('payments', 'tenant_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    nullable=True)
    op.drop_constraint('payments_tenant_id_fkey',
                       'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', [
                          'tenant_id'], ['id'], ondelete='SET NULL')
    op.drop_column('payments', 'payment_method')
    op.drop_column('payments', 'transaction_reference')
    op.drop_column('payments', 'tenant_name')
    op.drop_column('payments', 'notes')
    op.alter_column('properties', 'status',
                    existing_type=postgresql.ENUM(
                        'ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='propertystatus'),
                    nullable=False)
    op.alter_column('properties', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=False)
    op.drop_constraint('properties_user_id_fkey',
                       'properties', type_='foreignkey')
    op.create_foreign_key(None, 'properties', 'users', [
                          'user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('property_units_property_id_fkey',
                       'property_units', type_='foreignkey')
    op.create_foreign_key(None, 'property_units', 'properties', [
                          'property_id'], ['id'], ondelete='CASCADE')
    op.alter_column('tenants', 'user_id',
                    existing_type=sa.INTEGER(),
                    type_=sa.String(length=36),
                    existing_nullable=True)
    op.create_index(op.f('ix_tenants_status'),
                    'tenants', ['status'], unique=False)
    op.drop_constraint('tenants_user_id_fkey', 'tenants', type_='foreignkey')
    op.drop_constraint('tenants_current_property_id_fkey',
                       'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'users', [
                          'user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tenants', 'properties', [
                          'current_property_id'], ['id'], ondelete='SET NULL')
    op.alter_column('users', 'first_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('users', 'last_name',
                    existing_type=sa.VARCHAR(),
                    nullable=True)
    op.drop_column('users', 'auth_provider_id')
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password',
                  sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('auth_provider_id',
                  sa.UUID(), autoincrement=False, nullable=True))
    op.alter_column('users', 'last_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'first_name',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('users', 'id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    existing_nullable=False,
                    existing_server_default=sa.text("nextval('users_id_seq'::regclass)"))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key('tenants_current_property_id_fkey',
                          'tenants', 'properties', ['current_property_id'], ['id'])
    op.create_foreign_key('tenants_user_id_fkey',
                          'tenants', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.alter_column('tenants', 'user_id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    existing_nullable=True)
    op.drop_constraint(None, 'property_units', type_='foreignkey')
    op.create_foreign_key('property_units_property_id_fkey',
                          'property_units', 'properties', ['property_id'], ['id'])
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.create_foreign_key('properties_user_id_fkey',
                          'properties', 'users', ['user_id'], ['id'])
    op.alter_column('properties', 'user_id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    existing_nullable=False)
    op.alter_column('properties', 'status',
                    existing_type=postgresql.ENUM(
                        'ACTIVE', 'INACTIVE', 'DRAFT', 'ARCHIVED', name='propertystatus'),
                    nullable=True)
    op.add_column('payments', sa.Column(
        'notes', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column(
        'tenant_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('transaction_reference',
                  sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_method',
                  sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_tenant_id_fkey',
                          'payments', 'tenants', ['tenant_id'], ['id'])
    op.alter_column('payments', 'tenant_id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.alter_column('payments', 'status',
                    existing_type=postgresql.ENUM(
                        'PENDING', 'PAID', 'LATE', 'PARTIAL', 'OVERDUE', 'REFUNDED', name='paymentstatus'),
                    nullable=False)
    op.alter_column('payments', 'payment_date',
                    existing_type=sa.Date(),
                    type_=postgresql.TIMESTAMP(),
                    existing_nullable=False)
    op.drop_column('payments', 'description')
    op.drop_index(op.f('ix_leases_tenant_id'), table_name='leases')
    op.drop_index(op.f('ix_leases_status'), table_name='leases')
    op.drop_index(op.f('ix_leases_property_id'), table_name='leases')
    op.drop_constraint(None, 'lease_documents', type_='foreignkey')
    op.drop_constraint(None, 'lease_documents', type_='foreignkey')
    op.create_foreign_key('lease_documents_uploaded_by_id_fkey',
                          'lease_documents', 'users', ['uploaded_by_id'], ['id'])
    op.create_foreign_key('lease_documents_lease_id_fkey',
                          'lease_documents', 'leases', ['lease_id'], ['id'])
    op.alter_column('lease_documents', 'uploaded_by_id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.alter_column('lease_documents', 'lease_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.create_foreign_key('invoices_tenant_id_fkey',
                          'invoices', 'users', ['tenant_id'], ['id'])
    op.alter_column('invoices', 'tenant_id',
                    existing_type=sa.String(length=36),
                    type_=sa.INTEGER(),
                    nullable=False)
    op.add_column('expenses', sa.Column(
        'vendor_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
