"""add_receipt_url_to_payments_table

Revision ID: a630e93e0aa3
Revises: c27f33a146fb
Create Date: 2025-06-03 13:01:37.213848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# It's good practice to import sqlmodel if you might use its specific types,
# but for simple String, sa.String is sufficient and standard.
# import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a630e93e0aa3'
down_revision: Union[str, None] = 'c27f33a146fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Adds a nullable 'receipt_url' column to the 'payments' table.
    
    This migration updates the database schema to include a new string column for storing receipt URLs associated with payments.
    """
    op.add_column('payments', sa.Column(
        'receipt_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Reverts the schema change by removing the 'receipt_url' column from the 'payments' table.
    """
    op.drop_column('payments', 'receipt_url')
    # ### end Alembic commands ###
