"""Add full_name to tenants

Revision ID: ace546425e32
Revises: f0d16aacf146
Create Date: 2025-04-09 23:41:22.878860

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace546425e32'
down_revision: Union[str, None] = 'f0d16aacf146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add full_name with a default value to avoid null constraint violation
    op.add_column('tenants', sa.Column(
        'full_name',
        sqlmodel.sql.sqltypes.AutoString(),
        nullable=False,
        server_default=''
    ))

    # Add the rest of the new columns
    op.add_column('tenants', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('unit_id', sa.Integer(), nullable=True))
    op.add_column('tenants', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('tenants', sa.Column('lease_start', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('lease_end', sa.Date(), nullable=True))
    op.add_column('tenants', sa.Column('monthly_rent', sa.Float(), nullable=True))

    # Adjust constraints and foreign keys
    op.alter_column('tenants', 'user_id', existing_type=sa.INTEGER(), nullable=True)
    op.drop_constraint('tenants_user_id_key', 'tenants', type_='unique')
    op.drop_constraint('tenants_current_unit_id_fkey', 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'property_units', ['unit_id'], ['id'])

    # Drop deprecated columns
    op.drop_column('tenants', 'current_unit_id')
    op.drop_column('tenants', 'move_out_date')
    op.drop_column('tenants', 'move_in_date')
    op.drop_column('tenants', 'phone_number')

    # Optional: remove default if you don’t want future inserts to use ''
    op.alter_column('tenants', 'full_name', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('move_in_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('move_out_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('current_unit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key('tenants_current_unit_id_fkey', 'tenants', 'property_units', ['current_unit_id'], ['id'])
    op.create_unique_constraint('tenants_user_id_key', 'tenants', ['user_id'])
    op.alter_column('tenants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tenants', 'monthly_rent')
    op.drop_column('tenants', 'lease_end')
    op.drop_column('tenants', 'lease_start')
    op.drop_column('tenants', 'unit')
    op.drop_column('tenants', 'unit_id')
    op.drop_column('tenants', 'phone')
    op.drop_column('tenants', 'full_name')
    # ### end Alembic commands ###
