"""Sync database with current model state

Revision ID: afe06420ef77
Revises: e7a3c2b1f0d9
Create Date: 2025-06-14 06:50:54.553203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'afe06420ef77'
down_revision: Union[str, None] = 'e7a3c2b1f0d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Applies schema changes to synchronize the database with the current model state.
    
    This migration alters column types and precisions, adds unique constraints, and creates indexes on various tables to improve data integrity and query performance. It also updates the foreign key constraint on the `tenants.landlord_id` column.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    # Skip dropping wrappers_fdw_stats as it's owned by the wrappers extension
    # op.drop_table('wrappers_fdw_stats')
    op.alter_column('expense_tax_details', 'tax_rate',
               existing_type=sa.NUMERIC(precision=6, scale=4),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=False)
    op.alter_column('expenses', 'quickbooks_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_unique_constraint('expenses_quickbooks_id_key', 'expenses', ['quickbooks_id'])
    op.alter_column('invoices', 'quickbooks_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_invoices_last_synced_at'), 'invoices', ['last_synced_at'], unique=False)
    op.create_index('ix_invoices_property_id', 'invoices', ['property_id'], unique=False)
    op.create_index(op.f('ix_invoices_quickbooks_id'), 'invoices', ['quickbooks_id'], unique=True)
    op.create_index('ix_invoices_tenant_id', 'invoices', ['tenant_id'], unique=False)
    op.create_index('ix_lease_documents_lease_id', 'lease_documents', ['lease_id'], unique=False)
    op.create_index('ix_leases_unit_id', 'leases', ['unit_id'], unique=False)
    op.create_index('ix_maintenance_requests_property_id', 'maintenance_requests', ['property_id'], unique=False)
    op.create_index('ix_maintenance_requests_tenant_id', 'maintenance_requests', ['tenant_id'], unique=False)
    op.create_index('ix_maintenance_requests_unit_id', 'maintenance_requests', ['unit_id'], unique=False)
    op.create_index('ix_maintenance_requests_user_id', 'maintenance_requests', ['user_id'], unique=False)
    op.alter_column('payments', 'quickbooks_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_payments_quickbooks_id'), 'payments', ['quickbooks_id'], unique=True)
    op.create_index('ix_payments_tenant_id', 'payments', ['tenant_id'], unique=False)
    op.create_index('ix_properties_user_id', 'properties', ['user_id'], unique=False)
    op.create_index('ix_property_units_property_id', 'property_units', ['property_id'], unique=False)
    op.create_index('ix_property_units_tenant_id', 'property_units', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_unit_link_unit_id', 'tenant_unit_link', ['unit_id'], unique=False)
    op.alter_column('tenants', 'profile_image_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('tenants', 'quickbooks_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index('ix_tenants_current_property_id', 'tenants', ['current_property_id'], unique=False)
    op.drop_constraint(op.f('tenants_landlord_id_fkey'), 'tenants', type_='foreignkey')
    op.create_foreign_key('tenants_landlord_id_fkey', 'tenants', 'users', ['landlord_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Reverts the database schema to its previous state before the current migration.
    
    This function undoes changes made in the corresponding upgrade, including reverting column types, dropping indexes and unique constraints, and restoring original foreign key constraints and behaviors.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tenants_landlord_id_fkey', 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_landlord_id_fkey'), 'tenants', 'users', ['landlord_id'], ['id'], ondelete='SET NULL')
    op.drop_index('ix_tenants_current_property_id', table_name='tenants')
    op.alter_column('tenants', 'quickbooks_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('tenants', 'profile_image_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('ix_tenant_unit_link_unit_id', table_name='tenant_unit_link')
    op.drop_index('ix_property_units_tenant_id', table_name='property_units')
    op.drop_index('ix_property_units_property_id', table_name='property_units')
    op.drop_index('ix_properties_user_id', table_name='properties')
    op.drop_index('ix_payments_tenant_id', table_name='payments')
    op.drop_index(op.f('ix_payments_quickbooks_id'), table_name='payments')
    op.alter_column('payments', 'quickbooks_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index('ix_maintenance_requests_user_id', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_requests_unit_id', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_requests_tenant_id', table_name='maintenance_requests')
    op.drop_index('ix_maintenance_requests_property_id', table_name='maintenance_requests')
    op.drop_index('ix_leases_unit_id', table_name='leases')
    op.drop_index('ix_lease_documents_lease_id', table_name='lease_documents')
    op.drop_index('ix_invoices_tenant_id', table_name='invoices')
    op.drop_index(op.f('ix_invoices_quickbooks_id'), table_name='invoices')
    op.drop_index('ix_invoices_property_id', table_name='invoices')
    op.drop_index(op.f('ix_invoices_last_synced_at'), table_name='invoices')
    op.alter_column('invoices', 'quickbooks_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_constraint('expenses_quickbooks_id_key', 'expenses', type_='unique')
    op.alter_column('expenses', 'quickbooks_id',
               existing_type=sa.String(length=64),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('expense_tax_details', 'tax_rate',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.NUMERIC(precision=6, scale=4),
               existing_nullable=False)
    # Skip creating wrappers_fdw_stats as it's owned by the wrappers extension
    # op.create_table('wrappers_fdw_stats',
    # sa.Column('fdw_name', sa.TEXT(), autoincrement=False, nullable=False),
    # sa.Column('create_times', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total number of times the FDW instacne has been created'),
    # sa.Column('rows_in', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total rows input from origin'),
    # sa.Column('rows_out', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total rows output to Postgres'),
    # sa.Column('bytes_in', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total bytes input from origin'),
    # sa.Column('bytes_out', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total bytes output to Postgres'),
    # sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Metadata specific for the FDW'),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    # sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    # sa.PrimaryKeyConstraint('fdw_name', name=op.f('wrappers_fdw_stats_pkey')),
    # comment='Wrappers Foreign Data Wrapper statistics'
    # )
    # ### end Alembic commands ###
