"""Create New Tenant without user_id

Revision ID: b1c050b82416
Revises: 498bda312b0f
Create Date: 2025-04-15 04:48:17.362234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1c050b82416'
down_revision: Union[str, None] = '498bda312b0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index('ix_tenants_user_id', table_name='tenants')
    op.create_index(op.f('ix_tenants_user_id'), 'tenants', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenants_user_id'), table_name='tenants')
    op.create_index('ix_tenants_user_id', 'tenants', ['user_id'], unique=True)
    op.alter_column('tenants', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
