"""adding tenant_id to property_units table

Revision ID: b4637ec85bb2
Revises: 1a5936625dc8
Create Date: 2025-04-20 05:15:35.205813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4637ec85bb2'
down_revision: Union[str, None] = '1a5936625dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_units', sa.Column(
        'tenant_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'property_units',
                          'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'property_units', type_='foreignkey')
    op.drop_column('property_units', 'tenant_id')
    # ### end Alembic commands ###
