"""NewPropertyModal Upgrade

Revision ID: b94902d0de17
Revises: d70e4f5465dc
Create Date: 2025-04-18 05:46:03.581071

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b94902d0de17'
down_revision: Union[str, None] = 'd70e4f5465dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('properties', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('properties', 'zip_code')
    op.drop_column('properties', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('properties', sa.Column('zip_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('properties', 'postal_code')
    op.drop_column('properties', 'province')
    # ### end Alembic commands ###
