"""add_payment_method_and_transaction_reference_to_payments_table

Revision ID: c27f33a146fb
Revises: e4c97731a713
Create Date: 2025-05-31 15:31:36.022528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c27f33a146fb'
down_revision: Union[str, None] = 'e4c97731a713'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Applies schema changes to make certain columns nullable and add new columns.

    This migration makes the 'status' column in 'invoices' non-nullable, allows null values for 'tenant_id' in 'invoices' and 'payments', and for 'uploaded_by_id' in 'lease_documents'. It also adds 'payment_method' and 'transaction_reference' columns to the 'payments' table.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoices', 'status',
                    existing_type=postgresql.ENUM(
                        'Pending', 'Paid', 'Partial', 'Overdue', 'Cancelled', 'Refunded', name='paymentstatus'),
                    nullable=False,
                    existing_server_default=sa.text("'Pending'::paymentstatus"))
    op.alter_column('invoices', 'tenant_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=True)
    op.alter_column('lease_documents', 'uploaded_by_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=True)
    op.add_column('payments', sa.Column(
        'payment_method', sa.String(), nullable=True))
    op.add_column('payments', sa.Column(
        'transaction_reference', sa.String(), nullable=True))
    op.alter_column('payments', 'tenant_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Reverts the database schema changes made in the corresponding upgrade.

    This function restores previous column nullability and removes columns added during the upgrade, ensuring the schema matches its prior state.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'tenant_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=False)
    op.drop_column('payments', 'transaction_reference')
    op.drop_column('payments', 'payment_method')
    op.alter_column('lease_documents', 'uploaded_by_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=False)
    op.alter_column('invoices', 'tenant_id',
                    existing_type=sa.VARCHAR(length=36),
                    nullable=False)
    op.alter_column('invoices', 'status',
                    existing_type=postgresql.ENUM(
                        'Pending', 'Paid', 'Partial', 'Overdue', 'Cancelled', 'Refunded', name='paymentstatus'),
                    nullable=True,
                    existing_server_default=sa.text("'Pending'::paymentstatus"))
    # ### end Alembic commands ###
