"""Add user agent threads table

Revision ID: c4d6a02c4765
Revises: be84796fc7de
Create Date: 2025-06-25 04:21:38.997541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4d6a02c4765'
down_revision: Union[str, None] = 'be84796fc7de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_agent_threads',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_active', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('conversation_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_agent_threads_thread_id'), 'user_agent_threads', ['thread_id'], unique=False)
    op.create_index(op.f('ix_user_agent_threads_user_id'), 'user_agent_threads', ['user_id'], unique=False)
    # Removed: op.drop_table('wrappers_fdw_stats') - this is a Supabase system table
    op.drop_constraint(op.f('expenses_quickbooks_id_key'), 'expenses', type_='unique')
    op.create_index(op.f('ix_expenses_quickbooks_id'), 'expenses', ['quickbooks_id'], unique=True)
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('Pending', 'Paid', 'Partial', 'Overdue', 'Cancelled', 'Refunded', 'Draft', 'Void', 'Uncollectible', name='paymentstatus'),
               nullable=True,
               existing_server_default=sa.text("'Pending'::paymentstatus"))
    op.alter_column('properties', 'property_type',
               existing_type=postgresql.ENUM('Residential', 'Commercial', 'Industrial', 'Land', 'Special Purpose', 'Mixed-Use', 'Apartment Complex', 'Other', name='property_type_enum'),
               type_=sa.String(length=50),
               nullable=True,
               comment=None,
               existing_comment='Type of property using PropertyType enum')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('properties', 'property_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('Residential', 'Commercial', 'Industrial', 'Land', 'Special Purpose', 'Mixed-Use', 'Apartment Complex', 'Other', name='property_type_enum'),
               nullable=False,
               comment='Type of property using PropertyType enum')
    op.alter_column('invoices', 'status',
               existing_type=postgresql.ENUM('Pending', 'Paid', 'Partial', 'Overdue', 'Cancelled', 'Refunded', 'Draft', 'Void', 'Uncollectible', name='paymentstatus'),
               nullable=False,
               existing_server_default=sa.text("'Pending'::paymentstatus"))
    op.drop_index(op.f('ix_expenses_quickbooks_id'), table_name='expenses')
    op.create_unique_constraint(op.f('expenses_quickbooks_id_key'), 'expenses', ['quickbooks_id'], postgresql_nulls_not_distinct=False)
    # Removed: op.create_table('wrappers_fdw_stats') - this is a Supabase system table
    op.drop_index(op.f('ix_user_agent_threads_user_id'), table_name='user_agent_threads')
    op.drop_index(op.f('ix_user_agent_threads_thread_id'), table_name='user_agent_threads')
    op.drop_table('user_agent_threads')
    # ### end Alembic commands ###
