"""added is_email_verified to users

Revision ID: d6d56ec874b9
Revises: 2029f6b30dbe
Create Date: 2025-04-19 06:40:53.329743

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d56ec874b9'
down_revision: Union[str, None] = '2029f6b30dbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_email_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'otp_expires_at')
    op.drop_column('users', 'phone_otp_hash')
    op.drop_column('users', 'is_phone_verified')
    op.drop_column('users', 'is_email_verified')
    # ### end Alembic commands ###
