"""Unit model cleanup

Revision ID: d70e4f5465dc
Revises: 314d2daafae0
Create Date: 2025-04-17 21:51:16.711691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd70e4f5465dc'
down_revision: Union[str, None] = '314d2daafae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property_units', sa.Column('floor', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property_units', 'floor')
    # ### end Alembic commands ###
