"""create_maintenance_requests_table

Revision ID: e7a3c2b1f0d9
Revises: 0ae9ec6ef664
Create Date: YYYY-MM-DD HH:MM:SS.ffffff

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7a3c2b1f0d9'
down_revision = '0ae9ec6ef664'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Creates the maintenance_requests table, related ENUM types, and a trigger for automatic timestamp updates.
    
    Defines the maintenance_priority and maintenance_status ENUM types, creates the maintenance_requests table with appropriate columns and constraints, and sets up a trigger to automatically update the updated_at timestamp on row modifications.
    """
    op.execute("""
    CREATE TYPE maintenance_priority AS ENUM ('Low', 'Medium', 'High');
    """)
    op.execute("""
    CREATE TYPE maintenance_status AS ENUM ('Pending', 'In Progress', 'Scheduled', 'Completed', 'Cancelled');
    """)
    op.create_table('maintenance_requests',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('issue_title', sa.String(
                        length=255), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('property_id', sa.Integer(), nullable=False),
                    sa.Column('unit_id', sa.Integer(), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.UUID(), nullable=True),
                    sa.Column('request_date', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('priority', sa.Enum('Low', 'Medium', 'High',
                                                  name='maintenance_priority'), nullable=False),
                    sa.Column('status', sa.Enum('Pending', 'In Progress', 'Scheduled', 'Completed',
                                                'Cancelled', name='maintenance_status'), server_default='Pending', nullable=False),
                    sa.Column('scheduled_date', sa.Date(), nullable=True),
                    sa.Column('estimated_cost', sa.Numeric(
                        precision=10, scale=2), nullable=True),
                    sa.Column('actual_cost', sa.Numeric(
                        precision=10, scale=2), nullable=True),
                    sa.Column('photos', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(timezone=True),
                              server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
                    sa.Column('assigned_to', sa.String(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['property_id'], ['properties.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
                    sa.ForeignKeyConstraint(
                        ['unit_id'], ['property_units.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['users.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.execute("""
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $$
    BEGIN
       NEW.updated_at = NOW();
       RETURN NEW;
    END;
    $$ language 'plpgsql';
    """)
    op.execute("""
    CREATE TRIGGER update_maintenance_requests_updated_at
    BEFORE UPDATE ON maintenance_requests
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Reverts the database schema changes made by the upgrade function.
    
    Drops the `maintenance_requests` table, associated ENUM types, and the trigger and function for automatic timestamp updates.
    """
    op.execute(
        "DROP TRIGGER IF EXISTS update_maintenance_requests_updated_at ON maintenance_requests;")
    op.execute("DROP FUNCTION IF EXISTS update_updated_at_column();")
    op.drop_table('maintenance_requests')
    op.execute("DROP TYPE IF EXISTS maintenance_status;")
    op.execute("DROP TYPE IF EXISTS maintenance_priority;")
    # ### end Alembic commands ###
