"""Add current_unit_id to tenants table

Revision ID: f9fe37e85832
Revises: 6e85a0b7b420
Create Date: 2025-04-08 05:22:55.980143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9fe37e85832'
down_revision: Union[str, None] = '6e85a0b7b420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('leases_tenant_id_fkey', 'leases', type_='foreignkey')
    op.create_foreign_key(None, 'leases', 'tenants', ['tenant_id'], ['id'])
    op.add_column('tenants', sa.Column('current_unit_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'property_units', ['current_unit_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'current_unit_id')
    op.drop_constraint(None, 'leases', type_='foreignkey')
    op.create_foreign_key('leases_tenant_id_fkey', 'leases', 'users', ['tenant_id'], ['id'])
    # ### end Alembic commands ###
