"on":
  pull_request:
    branches:
      - main
    paths:
      - "**"
      - "!.github/workflows/porter_**"
name: Deploy to Preview Environment
jobs:
  porter-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set Github tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Copy Poetry files to Backend for Docker build
        run: |
          echo "Copying poetry files to Backend directory..."
          cp pyproject.toml Backend/
          cp poetry.lock Backend/
          echo "Poetry files copied successfully."
      - name: Setup porter
        uses: porter-dev/setup-porter@v0.1.0
      - name: List files in workspace # Debug
        run: |
          echo "Current directory: $(pwd)"
          ls -la
          find . -type f
      - name: Build and deploy preview environment
        timeout-minutes: 30
        run: exec porter apply --preview
        env:
          PORTER_APP_NAME: brikli-backend-prod
          PORTER_CLUSTER: "4829"
          PORTER_HOST: https://dashboard.porter.run
          PORTER_PR_NUMBER: ${{ github.event.number }}
          PORTER_PROJECT: "15766"
          PORTER_REPO_NAME: ${{ github.event.repository.name }}
          PORTER_TAG: ${{ steps.vars.outputs.sha_short }}
          PORTER_TOKEN: ${{ secrets.PORTER_APP_15766_4829 }}
